name: sudan_passport_photo
description: Passport photo application for Sudan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: 2.6.1

  
  # Camera & ML
  camera: 0.11.0+2
  google_mlkit_face_detection: 0.12.0
  google_mlkit_subject_segmentation: 0.0.1
  
  # Image Processing
  image: 4.3.0
  flutter_image_compress: 2.3.0
  
  # Export
  pdf: 3.11.1
  path_provider: 2.1.5
  
  # UI
  google_fonts: 6.2.1
  
  # Permissions
  permission_handler: 11.3.1
  
  # Utils
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

